### ISSUE TITLE
感谢你的工作

### ISSUE THREAD

**Issue by hehh2001** [SivanLaai/rime_pure#1]
你好我PC一直在用fcitx，最近手机换成安卓了， 苦于找不到好的输入法，追过来了，感谢你的工作！
我部署了九宫四叶拼音，可输入不了汉字，全是数字，要改哪个配置文件吗？

**Comment by hehh2001** [comment]
报歉，没看仔细，已经解决了，九宫输入法是以四叶拼音为基础，我没覆盖全，只考了九宫拼音

**Comment by SivanLaai** [comment]
报歉，现在才看到消息，照着教程来应该没问题
