### ISSUE TITLE
可否增加一个微软双拼的九宫格输入法配置

### ISSUE THREAD

**Issue by tempso** [SivanLaai/rime_pure#13]
非常感谢您，九宫格拼音非常顺畅，可否增加一个微软双拼的九宫格配置？我希望悬浮窗口是竖排的，这样重码时候可以更方便的选择，谢谢。

**Comment by SivanLaai** [comment]
这个可能需要点时间来做，我有时间给做出来，可能需要稍等一下，多谢反馈。

**Comment by SivanLaai** [comment]
增加了小鹤双拼的九宫配置
