### ISSUE TITLE
关于 小狼毫 的 小鹤双拼词库问题

### ISSUE THREAD

**Issue by dexiaobu** [SivanLaai/rime_pure#14]
不知道是我自己配置的问题还是词库收录漏掉了，求解。
在输入 ui 时想打出 “事” 这个词，但发现找不到，使用反查时发现 “事” 字存在但没有对应编码。
尝试重装后还是打不出这个字，只能使用词的方式打出单字。
而且在手机版的同文输入法中也有同样的问题。

![Snipaste_2021-01-24_15-59-32](https://user-images.githubusercontent.com/40593562/105624540-51117480-5e5d-11eb-87f2-2b5ac01bf727.png)

**Comment by SivanLaai** [comment]
多谢反馈，已经修正。
![image](https://user-images.githubusercontent.com/33414148/105934172-9f578b00-608a-11eb-8c94-e76840abbf60.png)

**Comment by dexiaobu** [comment]
> 多谢反馈，已经修正。
> ![image](https://user-images.githubusercontent.com/33414148/105934172-9f578b00-608a-11eb-8c94-e76840abbf60.png)

🙏🏻️感谢修正，没想到那么快就修复了。

另外还有一个小小的问题不知道能否看一下。
就是在 _某些自定义方案_ 中 **无法使用快捷方式打出符号** 。

比如我想打 六十四卦爻的符号，在原生界面只需要输入 /lssg 就可以出现符号列表。
测试了一下，在 徐码 和 小鹤音形 中无法这样进行输入，但是在 郑码 和 拼音 并没有问题：
![Snipaste_2021-01-27_15-58-43](https://user-images.githubusercontent.com/40593562/105960695-8cf44600-60b8-11eb-8aaf-444543eae206.png)

想了下应该是官方码表的原因，可能在某些方案中符号的输入已经有了自己的一套方案，比如徐码。
后来我尝试将 官方的基础配置（rime-prelude） 重新部署了一下发现徐码也可以启用快捷输入了，虽然符号后面多了反查的提示。
但是小鹤音形还是不行，而且小鹤无法切换繁体，可能是因为官方的挂载本身就不支持。不知道能否看一下 github 上的其他小鹤方案（如 rime-xhup ，虽然有些老了），说不定可以实现简繁的切换，让这个好方案的细节都更加统一。

**Comment by SivanLaai** [comment]
六十四卦爻的符号的原文件你有嗎
