### ISSUE TITLE
请问这个皮肤【炫彩[键盘布局：Jaaiko]】文件有吗，我下载的文件里面没找到

### ISSUE THREAD

**Issue by LvLaoTou** [SivanLaai/rime_pure#15]
![image](https://user-images.githubusercontent.com/53200809/105804140-ff422900-5fd9-11eb-9461-5a4174446ff9.png)

**Comment by LvLaoTou** [comment]
已经找到了，同文输入法可以在app里面设置主题

**Comment by SivanLaai** [comment]
抱歉，忙过了没有及时解答，多谢反馈。
