### ISSUE TITLE
同文风中“夜色”与“夜色2”背景图片损坏

### ISSUE THREAD

**Issue by tpjz** [SivanLaai/rime_pure#16]
如上所述，这两个背景图片中的空格键背景损坏了，因为我只用了“夜色”背景，所以仅述“夜色”修复方法。
在“backgrouds"文件夹中找到”YSkgb"和“YSkgh”两个文件，一个是常态背景，一个是按下去的背景，用Photoshop建一个350*170的透明图片，空格比例参考“backgrounds"中的其它”YSxxx"比例，保存成png格式替换即可。

**Comment by SivanLaai** [comment]
可以看一下你之前说的损坏的情况不，我这里夜色是正常的
![9a50b920544e7ada8e0cc5721e90ce7](https://user-images.githubusercontent.com/33414148/105935230-8c45ba80-608c-11eb-8426-272159e3880e.jpg)

**Comment by tpjz** [comment]
你好，我没及时查看邮件。以下是附图

Sivan <notifications@github.com> 于 2021年1月27日周三 10:44写道：
