### ISSUE TITLE
加载时间很久

### ISSUE THREAD

**Issue by evansan** [SivanLaai/rime_pure#17]
当第一次启动输入法的时候，最少需要10秒键盘才能出现，有时候甚至1分钟以上。当切换到其他输入法再切回来的时候也需要好几秒。
我用的是最新测试版，系统是LineageOS 18.1

**Comment by SivanLaai** [comment]
是第一次加载的时候还是每次用的时候都会？如果是第一次用的话是正常，毕竟有很多配置要加载。
PS：你说的来回切换的现象你能不能录个屏，我自己测试没有遇到这个情况
