### ISSUE TITLE
唤起九宫格方案后依旧是全键盘

### ISSUE THREAD

**Issue by HarryWang29** [SivanLaai/rime_pure#18]
![image](https://user-images.githubusercontent.com/8288067/106112238-f5f6bf00-6187-11eb-88ab-68f11afcabf6.png)
按照教程先装拼音，再装九宫格，也能正常唤起九宫格方案，但是界面显示全键盘，输入上面数字，可以使用输入法

**Comment by HarryWang29** [comment]
好像知道了，我使用的主题没有九宫格的布局？

**Comment by HarryWang29** [comment]
不好意思，想问下能够支持一下五筆畫输入方案么

**Comment by SivanLaai** [comment]
你说的五笔是王码86这些五笔还是笔画的五笔？

**Comment by HarryWang29** [comment]
笔画的五笔

**Comment by SivanLaai** [comment]
好的，收到，我有时间研究一下看能否加进来。

**Comment by HarryWang29** [comment]
嗯嗯，麻烦了，我之前想自己搞一下，倒是搞了一半了

**Comment by SivanLaai** [comment]
如果你愿意的话，你可以提merge到这里来，这样大家就一起享用了。共同的成果大家一起享用，你也可以在作者栏加上你的信息。

**Comment by HarryWang29** [comment]
对于细节上掌控比较麻烦，不过基础功能好像已经可以使用了

**Comment by SivanLaai** [comment]
可以慢慢完善，这个项目也还在完善。

> 对于细节上掌控比较麻烦，不过基础功能好像已经可以使用了
> […](#)
> On Feb 1, 2021, 11:39 AM +0800, Sivan ***@***.***>, wrote: 如果你愿意的话，你可以提merge到这里来，这样大家就一起享用了。共同的成果大家一起享用，你也可以在作者栏加上你的信息。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HarryWang29** [comment]
> 可以慢慢完善，这个项目也还在完善。
> 
> > 对于细节上掌控比较麻烦，不过基础功能好像已经可以使用了
> > […](#)
> > On Feb 1, 2021, 11:39 AM +0800, Sivan ***@***.***>, wrote: 如果你愿意的话，你可以提merge到这里来，这样大家就一起享用了。共同的成果大家一起享用，你也可以在作者栏加上你的信息。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 

可以这样![Screenshot_20210201-114623.jpg](https://user-images.githubusercontent.com/8288067/106412688-440b0b80-6483-11eb-82c7-38130560f3b4.jpg)

**Comment by SivanLaai** [comment]
nice，可以。

**Comment by HarryWang29** [comment]
提pr了

**Comment by GoGoogle** [comment]
最后用的什么主题能够有九宫格布局？

> 好像知道了，我使用的主题没有九宫格的布局？

**Comment by HarryWang29** [comment]
> 最后用的什么主题能够有九宫格布局？
> 
> > 好像知道了，我使用的主题没有九宫格的布局？

名字不记得了，最后我就是使用上面图中的黑色的

**Comment by GoGoogle** [comment]
> > 最后用的什么主题能够有九宫格布局？
> > > 好像知道了，我使用的主题没有九宫格的布局？
> 
> 名字不记得了，最后我就是使用上面图中的黑色的

尴尬了，我现在就碰到了这个问题，不知道怎么解决

**Comment by HarryWang29** [comment]
> > > 最后用的什么主题能够有九宫格布局？
> > > > 好像知道了，我使用的主题没有九宫格的布局？
> > 
> > 
> > 名字不记得了，最后我就是使用上面图中的黑色的
> 
> 尴尬了，我现在就碰到了这个问题，不知道怎么解决

我就是换主题解决的，我好想是外面另外找的，你试试看这个主题？如果方案没问题的话，应该是可以的
![image](https://user-images.githubusercontent.com/8288067/112410912-f7430300-8d56-11eb-9cdc-4c68174743ad.png)

**Comment by GoGoogle** [comment]
> > > > 最后用的什么主题能够有九宫格布局？
> > > > > 好像知道了，我使用的主题没有九宫格的布局？
> > > 
> > > 
> > > 名字不记得了，最后我就是使用上面图中的黑色的
> > 
> > 
> > 尴尬了，我现在就碰到了这个问题，不知道怎么解决
> 
> 我就是换主题解决的，我好想是外面另外找的，你试试看这个主题？如果方案没问题的话，应该是可以的
> ![image](https://user-images.githubusercontent.com/8288067/112410912-f7430300-8d56-11eb-9cdc-4c68174743ad.png)

这是哪个主题？

**Comment by HarryWang29** [comment]
项目主页有，你看看

**Comment by GoGoogle** [comment]
> 项目主页有，你看看
> […](#)
> On Mar 25, 2021, 10:42 PM +0800, GoGoogle ***@***.***>, wrote: > > > > 最后用的什么主题能够有九宫格布局？ > > > > > 好像知道了，我使用的主题没有九宫格的布局？ > > > 名字不记得了，最后我就是使用上面图中的黑色的 > > 尴尬了，我现在就碰到了这个问题，不知道怎么解决 > 我就是换主题解决的，我好想是外面另外找的，你试试看这个主题？如果方案没问题的话，应该是可以的 这是哪个主题？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

最终我只能放弃了，没有那个调教的能力。

**Comment by HarryWang29** [comment]
这么遗憾
