### ISSUE TITLE
四葉草九宮格候選詞範圍可否向下延展，方便選詞；拼音選項也可在候選詞左側列出

### ISSUE THREAD

**Issue by imapproxy** [SivanLaai/rime_pure#20]
如圖所示，點擊右上角紅色框內三點，候選詞範圍向下延展，且左側可依次選擇長詞中各字的拼音候選項。
謝謝作者貢獻這個九宮格，以前裝了同文，總是因爲用起來太不方便，不得不選擇其他有隱私疑慮的輸入法。
其實已經可以使用了，如果能進一步優化，就更完美了。

![涂鸦_Screenshot_2021-02-26-19-45-29-666_相册](https://user-images.githubusercontent.com/40516405/109296876-0758e700-786c-11eb-91cf-8147c1e65df3.jpg)
![Screenshot_2021-02-26-19-45-42-539_相册](https://user-images.githubusercontent.com/40516405/109296871-04f68d00-786c-11eb-8600-1af91ac06065.png)

**Comment by blackhole889** [comment]
完全同意这个意见，选词后准确度可以大大提高。希望有人可以早日做出来。如果有苹果讯飞那样的九宫设计和选词就好了。以后电脑手机就可以统一使用这个输入法了。另外很多手机上显示简/繁,半角/全角这样的图标。在手机上完全没必要。可以使用特殊组合显示出这个设置，平时不要有，本来手机屏幕就小。我们的软件界面工业设计还是与国际一流有距离。

**Comment by SivanLaai** [comment]
现在的键盘逻辑是把所有的按键是当成一个键的，所以要改动基本的框架，但是也可以实现，就是这个改动可能工作量就会很大了，我会花时间研究一下。

**Comment by imapproxy** [comment]
> 现在的键盘逻辑是把所有的按键是当成一个键的，所以要改动基本的框架，但是也可以实现，就是这个改动可能工作量就会很大了，我会花时间研究一下。

不知道選字選詞空間擴展和拼音選擇是不是一個問題。
如果兩個一起實現有難度，可以先實現選字/選詞空間擴展，拼音選擇先緩一緩。

因爲現在的單排選字/選詞的展示面積實在太小，能解決掉就能帶來體驗上相當大的提升。
拼音選擇相對前者算是錦上添花。

**Comment by SivanLaai** [comment]
好的，这个我先研究下，然后看看方案的实施难度。

**Comment by SivanLaai** [comment]
> > 现在的键盘逻辑是把所有的按键是当成一个键的，所以要改动基本的框架，但是也可以实现，就是这个改动可能工作量就会很大了，我会花时间研究一下。
> 
> 不知道選字選詞空間擴展和拼音選擇是不是一個問題。
> 如果兩個一起實現有難度，可以先實現選字/選詞空間擴展，拼音選擇先緩一緩。
> 
> 因爲現在的單排選字/選詞的展示面積實在太小，能解決掉就能帶來體驗上相當大的提升。
> 拼音選擇相對前者算是錦上添花。

我花了时间看了一下trime的源码，我看到有很多可以修改的地方，你说的这个加入下拉的选词菜单我应该可以实现，不过改动难度还是有的。
我会花时间去搞定，然后制作出一个基于同文的输入法。同时我也考虑加入联想功能，同时以后考虑语音输入和表情包的支持。我会重新建一个项目来发布输入法，这个项目会继续提供方案和皮肤。
多谢你的支持和建议。

**Comment by imapproxy** [comment]
> > > 现在的键盘逻辑是把所有的按键是当成一个键的，所以要改动基本的框架，但是也可以实现，就是这个改动可能工作量就会很大了，我会花时间研究一下。
> > 
> > 
> > 不知道選字選詞空間擴展和拼音選擇是不是一個問題。
> > 如果兩個一起實現有難度，可以先實現選字/選詞空間擴展，拼音選擇先緩一緩。
> > 因爲現在的單排選字/選詞的展示面積實在太小，能解決掉就能帶來體驗上相當大的提升。
> > 拼音選擇相對前者算是錦上添花。
> 
> 我花了时间看了一下trime的源码，我看到有很多可以修改的地方，你说的这个加入下拉的选词菜单我应该可以实现，不过改动难度还是有的。
> 我会花时间去搞定，然后制作出一个基于同文的输入法。同时我也考虑加入联想功能，同时以后考虑语音输入和表情包的支持。我会重新建一个项目来发布输入法，这个项目会继续提供方案和皮肤。
> 多谢你的支持和建议。

<font size=24>
看到這樣的反饋可真是太好了，感謝。
一定會多多向朋友們推薦這股輸入法中的清流的。

下面是一些不專業的使用體驗。

聯想：可能無須再做這方面的開發。用了一段時間後，熟悉很多，也順手很多。發現可以在輸入的時候手動按一下分詞符號來輔助劃分詞組，這樣的話似乎聯想功能沒有那麼強烈的需求。當然如果是不聯網的聯想，肯定是沒問題的。畢竟商業輸入法的聯想功能可能是通過聯網實現的，帶來隱私疑慮。

語音輸入：好像也不用開發了。不知道是不是調用的手機系統內置的語音輸入，我這里長按編輯，會出現語音輸入選項，識別得還挺準確，就是隱藏得深了點。
![Screenshot_2021-04-14-03-51-54-195_Fennec](https://user-images.githubusercontent.com/40516405/114614580-4dacbd00-9cd7-11eb-8815-49294d566db3.png)

表情包：選單中的表情，默認值最好可以設置為關閉。本來選單面積就小，再有表情夾雜其中，實在有些干擾文字輸入。每次啓動後都要點一下，切換爲關閉狀態。

期待新項目會更好，再次感謝。
</font>

**Comment by SivanLaai** [comment]
已經修復了表情包顯示的問題，也支持最新的同文版本了。
