### ISSUE TITLE
手机四叶草无法输入中文,四叶草九宫正常.

### ISSUE THREAD

**Issue by superiums** [SivanLaai/rime_pure#21]
android. 四叶草26键无法输入中文,四叶草九宫正常.
打中文和英文一样,直接上屏英文字母. 
求指点.

**Comment by blackhole889** [comment]
换个主题试试。

**Comment by superiums** [comment]
试过的, 同文,讯飞,机械键盘 主题都一样.

**Comment by SivanLaai** [comment]
最好是使用同文的皮肤，你是从哪里下载的呢，你可以下载release版本的。https://github.com/SivanLaai/rime_pure/releases/tag/1.0.0

**Comment by SivanLaai** [comment]
先把对应的rime文件夹删除，再覆盖release下载的内容

**Comment by superiums** [comment]
是从release下载的. 
删除Rime文件夹,只复制release里面的配置过去,无法启动输入法.
所以,是保留原来的rime文件夹,然后覆盖过去的.

**Comment by SivanLaai** [comment]
现在问题解决了吗

**Comment by ddfengle** [comment]
我遇到的问题 删除原有rime文件夹下的文件后复制下载的内容 选择了四叶草喝四叶草九宫格 就会闪退  而且键盘的主题选择的是同文的
