### ISSUE TITLE
使用郑码方案，简体无效果

### ISSUE THREAD

**Issue by qiang-jin-jiu** [SivanLaai/rime_pure#25]
已设置简体
![图片](https://user-images.githubusercontent.com/62086176/119483812-f430b700-bd87-11eb-9163-a7d37701a683.png)
打字，如，输入`s`预期出现在第一选项的是“说”
![图片](https://user-images.githubusercontent.com/62086176/119483993-29d5a000-bd88-11eb-881c-949423c5da67.png)
输入`ob`预期第一选项是“会”
![图片](https://user-images.githubusercontent.com/62086176/119484061-3a861600-bd88-11eb-86a4-b82ac6b8f099.png)
以上情况中应出现在第一选项的字，后面都紧接着`~;`，不知是什么情况

请问这是什么问题，如何解决

**Comment by SivanLaai** [comment]
![image](https://user-images.githubusercontent.com/33414148/120619798-e9180e00-c48e-11eb-9de6-cee596c1089e.png)
![image](https://user-images.githubusercontent.com/33414148/120619831-f1704900-c48e-11eb-8c19-8513cbe995a7.png)
多谢反馈，这个问题因为是用的比较老版本的词典导致的，已经解决。
