### ISSUE TITLE
四葉草九宮格不能轉為繁體輸出嗎？

### ISSUE THREAD

**Issue by cowcfj** [SivanLaai/rime_pure#26]
為何四葉草拼音能行，四葉草九宮格不行？

**Comment by cowcfj** [comment]
照着四葉草的schema裏的相應代碼，成功打出繁體字。

  - name: zh_simp_s2t
    reset: 0
    states: [ 简, 繁 ]

**Comment by SivanLaai** [comment]
这个已经处理好了。
