### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by CrazyHaa** [SivanLaai/rime_pure#27]
把所有文件复制到同文v3.2.1已经无法无法使用了，会闪退，去trime看了一下，说是新的opencc文件夹里面的都是.ocd2的文件，旧版的方案是.ocd的文件

**Comment by SivanLaai** [comment]
多谢反馈，本人还没有更新最新的同文，已经在处理中了。

**Comment by SivanLaai** [comment]
> 把所有文件复制到同文v3.2.1已经无法无法使用了，会闪退，去trime看了一下，说是新的opencc文件夹里面的都是.ocd2的文件，旧版的方案是.ocd的文件

如果要紧急使用你先把opencc文件夹删除在部署可以。

**Comment by SivanLaai** [comment]
這個問題和ocd文件沒什麼關係。我已經在新版本上測試過了。

**Comment by SivanLaai** [comment]
新版本測試現在沒有這個問題了

**Comment by spphinslove** [comment]
我最新的两个同文版本都闪退
