### ISSUE TITLE
四叶草九宫格转26键后不能输出中文

### ISSUE THREAD

**Issue by sciolism-9** [SivanLaai/rime_pure#28]
转26键后点左上角转换为中文，但没有字词显示出来

发现九宫格时点击左上角转换为英文，会变成数字九宫格

皮肤是讯飞

**Comment by sciolism-9** [comment]
好吧，发现四叶草和九宫格版都开启，通过快捷键切换就行了

**Comment by SivanLaai** [comment]
皮肤就用默认的同文风优化的就可以，这个是同文的ascii码支持，只能开启了这个就默认所有的字符会变成英文或者数字的。不同于一般的中英切换。
