### ISSUE TITLE
建议增加关闭（收起）输入法键盘的按键

### ISSUE THREAD

**Issue by zzzely** [SivanLaai/rime_pure#29]
目前在手机上使用的时候会遇到一种情况，输入完毕后，不知道如何关闭键盘，这样键盘会盖住部分信息（例如提交的按钮）
建议在右上方加一个按键⬇️，可以关闭键盘。

**Comment by SivanLaai** [comment]
这个功能已经有了，就是你在全键盘下向上滑动字母G就可以关闭键盘，同时也支持复制粘贴操作。

**Comment by SivanLaai** [comment]
长按G是编辑界面，支持复制等编辑操作。

**Comment by zzzely** [comment]
> 这个功能已经有了，就是你在全键盘下向上滑动字母G就可以关闭键盘，同时也支持复制粘贴操作。

了解了，那在九宫格模式下有对应的操作么？

**Comment by SivanLaai** [comment]
九宫的好像还没设置，我会做一个修正，暂时你可以利用系统的返回键来关闭。感谢反馈。

**Comment by SivanLaai** [comment]
九宫已经增加了，你更新文件[同文风增强版.trime.yaml](https://github.com/SivanLaai/rime_pure/blob/master/trime/rime/%E5%90%8C%E6%96%87%E9%A3%8E%E5%A2%9E%E5%BC%BA%E7%89%88.trime.yaml)到rime文件下覆盖重新部署一下就可以了。
隐藏方式是，隐藏输入法：全键盘状态下按键G向上滑，九宫格状态下按[JKL]向上滑
