### ISSUE TITLE
能不能加一个单纯小鹤双拼的方案？

### ISSUE THREAD

**Issue by Jacobax** [SivanLaai/rime_pure#3]
不想要辅助形码，只想要双拼不想要音形
拜谢

**Comment by Jacobax** [comment]
还是习惯重码候选，形码应该是在这个基础上辅助而不是去掉

**Comment by SivanLaai** [comment]
你说的是纯双拼吗？还是说你只用小鹤的音的部分

**Comment by SivanLaai** [comment]
已经优化了，你可以看一下

**Comment by Jacobax** [comment]
> 你说的是纯双拼吗？还是说你只用小鹤的音的部分

是的我是想要纯双拼
试了下音形即使保留了重码候选，跟纯双拼的候选也不一样

**Comment by SivanLaai** [comment]
你说的是候选排序吗？

**Comment by reiuyfan** [comment]
The same request.
Github 上能找到的几乎都是音形 缺少单独音码方案 同样地谢意

**Comment by SivanLaai** [comment]
> The same request.
> Github 上能找到的几乎都是音形 缺少单独音码方案 同样地谢意

那是直接自然双拼，不需要形码的吧。

**Comment by reiuyfan** [comment]
> > The same request.
> > Github 上能找到的几乎都是音形 缺少单独音码方案 同样地谢意
> 
> 那是直接自然双拼，不需要形码的吧。

是的
