### ISSUE TITLE
只有文字候选，没有拼音候选

### ISSUE THREAD

**Issue by sunwgit** [SivanLaai/rime_pure#31]
没有搜狗那种顶部文字候选，左侧拼音候选，导致要翻好多次顶部文字候选才能找到目标

**Comment by SivanLaai** [comment]
这个是rime设计问题，rime的设计就是一次候选这些字的，如果要改的话可能就要改同文端甚至rime端的代码了。目前你可以结合分词来使用拼音，准确率会大大提升
