### ISSUE TITLE
四叶草很久没有维护了

### ISSUE THREAD

**Issue by spphinslove** [SivanLaai/rime_pure#32]
我在四叶草github下面看到很多提交四叶草拼音错误的地方，你能修改一下吗？不着不止是图上的两个
![涂鸦_Screenshot_2021-07-26-00-09-04-785_Firefox Nightly](https://user-images.githubusercontent.com/11383988/126905840-9a240691-e57b-4452-9f44-8c2d185c6d2c.png)

**Comment by SivanLaai** [comment]
你能辛苦整理一下这些错误吗？然后反馈在这个issue上，这个词库还有一个问题是有很多重复的词组，我目前已经在处理这个问题了。所以你要是有时间的话，可以把这些错误整理好来，我在这个issue下一并处理。

**Comment by spphinslove** [comment]
![图片](https://user-images.githubusercontent.com/11383988/126920863-a6954dcf-8772-492b-9685-b7d6df3d22d1.png)
四叶草库有PR的 你看看


> 
> 
> 你能辛苦整理一下这些错误吗？然后反馈在这个issue上，这个词库还有一个问题是有很多重复的词组，我目前已经在处理这个问题了。所以你要是有时间的话，可以把这些错误整理好来，我在这个issue下一并处理。

**Comment by SivanLaai** [comment]
了解。

**Comment by SivanLaai** [comment]
已经完成了修复。请查看最新更新说明。
