### ISSUE TITLE
四叶草九宫格方案不能使用简拼

### ISSUE THREAD

**Issue by theodore26** [SivanLaai/rime_pure#33]
将“基础文件”、“Clover四叶草拼音”和“Clover四叶草九宫格拼音”一起下载下来，合并后，切换到“Clover四叶草九宫格拼音”方案，依次输入数字4和数字5，没有候选字。
只有全拼时才会有候选字（例如依次输入数字4和数字3，显示“和”、“个”......）。
比较clover_jiugong.schema.yaml和clover.schema.yaml配置，在clover_jiugong.schema.yaml的speller - algebra配置项中增加
`- abbrev/^([a-z]).+$/$1/`
测试后，支持简拼。
请问是不是这样修改，另外clover.schema.yaml中还有一个
`- abbrev/^([zcs]h).+$/$1/`
请问这个配置的作用是什么？

**Comment by SivanLaai** [comment]
都是看成简码的意思，九宫格中没有添加这个功能。
`- abbrev/^([a-z]).+$/$1/`
就是会把单独的字母看成简码。
`- abbrev/^([zcs]h).+$/$1/`
就是会把zh sh ch看成是单独的简码。
已经完成修复，多谢反馈。
