### ISSUE TITLE
四叶草方案无法输入中文

### ISSUE THREAD

**Issue by mizhilaowang** [SivanLaai/rime_pure#4]
华为 mate 30 pro EMUI 11 ，Android 10
根据操作步骤操作，四叶草方案无法输入中文。
后续安装的 四叶草九宫格可以输入中文。

**Comment by SivanLaai** [comment]
有提示什么错误吗，没有的话，先把rime下的build文件夹删除，同时把rime下的default.custom.yaml删除，重新布署再试试。

**Comment by mizhilaowang** [comment]
感谢回复，但是根据您的建议，重新部署还是无法输入中文。
切换到四叶草方案时，没有任何错误提示，但是 状态栏不显示。
![WechatIMG37](https://user-images.githubusercontent.com/12626706/101426640-5449b300-3938-11eb-9388-0999ce4b3fc1.jpeg)

**Comment by SivanLaai** [comment]
这种情况一般是因为少安装东西了，要不就是因为这个方案文件损坏了，你基础文件和所有的字典都安装了吗。这个我刚才测试了一下，没有问题，你把rime的内容备份一下，删除rime，再重新安装拼音试试，先不安装九宫。
