### ISSUE TITLE
有没有可能做到通过选择来降低重码率

### ISSUE THREAD

**Issue by hjianhao** [SivanLaai/rime_pure#5]
九宫格重码率有些太高了，其他输入法可以通过选择拼音降低重码率，好像这个九宫格不可以。

**Comment by SivanLaai** [comment]
重码高的原因是因为词库大，拼音重码大也是没有办法的。如果想要不这么高的话，那只能换一个精简词库。有时间做一个精简的看看。

**Comment by hjianhao** [comment]
或者换个思路，实现一个精确九宫？ 比如1键有abc，那么b就是1，而a就是14，c就是12？ 这样通过两个键来精确输入拼音？同理2键有def，那么e就是2，d是21，f是23. 依次类推。  

这样只要把原来的字典做个转换，例如八的拼音是ba，那么就是1'14?

**Comment by yyu0378** [comment]
九宫格的重码率是很高的,其实可以参考google的输入法,在输入法的左侧显示可能拼音组合让用户选择.

**Comment by hjianhao** [comment]
> 九宫格的重码率是很高的,其实可以参考google的输入法,在输入法的左侧显示可能拼音组合让用户选择.

这个Rime引擎可能做不到。

**Comment by yyu0378** [comment]
> 
> 
> > 九宫格的重码率是很高的,其实可以参考google的输入法,在输入法的左侧显示可能拼音组合让用户选择.
> 
> 这个Rime引擎可能做不到。

那这样就很难,快速输入,我词组输入时通常要翻很多页,翻页按钮还很小,速度就提不上去.

**Comment by SivanLaai** [comment]
后续会考虑加上大选盘，同时如果是用拼音的话也可以考虑使用分词符，可以有效降低重码率。
