### ISSUE TITLE
自己打字造的词同步不到另一个手机。

### ISSUE THREAD

**Issue by hjianhao** [SivanLaai/rime_pure#6]
我再手机A打入一个词，”流云飞袖“，然后使用同步功能将词库同步到sync目录，我看用户词库已经有这个词。然后用FolderSync同步到网盘。另外一台手机B，用FolderSync将手机A的词库同步到sync目录。然后再再手机B的同文输入法进行同步。同步完成后，手机B在输入拼音，却没有这个词，看上去是没有同步过来。

**Comment by SivanLaai** [comment]
你看一下对应的设置是不是复制过去了，应该会生成一个clover.userdb，你直接把这个复制打包拷贝过去。

**Comment by hjianhao** [comment]
破案了，坚果云客户端同步文件有问题。 我改用FolderSync同步就可以了。
