### ISSUE TITLE
九宫格输入法如何记录用户输入的词

### ISSUE THREAD

**Issue by hjianhao** [SivanLaai/rime_pure#7]
我用九宫格输入“燕晗山”，输入了几次，这个词依然无法记录。 重码率高，还没法造词，有点难用啊。

**Comment by hjianhao** [comment]
我再电脑上用四叶草拼音，输入"燕晗山", 然后同步后会有个user.yaml，这个文件传到手机上后，手机同步后，就能输入这个词。

也就是说电脑上支持用户输入后造词，但是手机上的四叶草九宫格步支持输入后造词？

**Comment by SivanLaai** [comment]
支持，你常用的输入都会正常保留到用户自定义里面，这些是加密了的文件，这个是rime引擎做到的事情。

**Comment by SivanLaai** [comment]
重码率高这个是拼音的通病，你说的这种解决方案是可以降低重码，但是难度也上来了。也就是大家还得花时间去学习，这还不如全键盘，双拼呢。或者你直接上五笔也是可以。

**Comment by hjianhao** [comment]
> 支持，你常用的输入都会正常保留到用户自定义里面，这些是加密了的文件，这个是rime引擎做到的事情。

是不是有什么设置要设置？我打了几遍都记不下来。换成同文输入法预置的什么明月输入法就可以记录。

另外四叶草九宫格可以输入中文，四叶草全键盘的方案输入不了中文？切换到中英文都输出英文？

**Comment by SivanLaai** [comment]
我已经更新了这个功能，你再安装一下。自定义词会生成user.txt的文件，这个就是存储你的自定义词的地方。有频率排序
