### ISSUE TITLE
四叶草拼音/四叶草九宫无法输入中文

### ISSUE THREAD

**Issue by lgl017** [SivanLaai/rime_pure#8]
安装trime-3.1.3-20190930.apk，然后按说明复制trime\rime,schemes\基础文件,schemes\Clover四叶草拼音，打不出中文
再复制schemes\Clover四叶草九宫拼音，仍为全键盘，且打不出中文
Android 11
![Screenshot_20201217-095016](https://user-images.githubusercontent.com/27935867/102430165-b51a6f00-404d-11eb-8e65-b64bc875b017.jpg)
![Screenshot_20201217-095049](https://user-images.githubusercontent.com/27935867/102430175-b5b30580-404d-11eb-9f59-cb47dca3b3aa.jpg)
![Screenshot_20201217-095120](https://user-images.githubusercontent.com/27935867/102430188-b64b9c00-404d-11eb-9e9f-9f1fa639aad4.jpg)
![Screenshot_20201217-095126](https://user-images.githubusercontent.com/27935867/102430130-b2b81500-404d-11eb-9f5f-d6c55d9bb8ba.jpg)

**Comment by SivanLaai** [comment]
把你的rime文件夹截图，包括opencc和build子目录也单独载个图

**Comment by lgl017** [comment]
![image](https://user-images.githubusercontent.com/27935867/102561550-fc693400-410f-11eb-80ba-c22a7f8fefca.png)
![image](https://user-images.githubusercontent.com/27935867/102561577-0c811380-4110-11eb-922c-b4a23be87d0c.png)
![image](https://user-images.githubusercontent.com/27935867/102561606-14d94e80-4110-11eb-97c0-ebb9bc705e34.png)

**Comment by SivanLaai** [comment]
你这里是没有正常安装同文皮肤，我发布了一个编译版本，你直接去这里https://github.com/SivanLaai/rime_pure/releases/tag/1.0.0下载，把trime.7z下的rime在覆盖你的rime文件夹就可以。

**Comment by lgl017** [comment]
目前我九宫还是不行，拼音可以了
操作流程：
直接覆盖后闪退
卸载同文，删除rime文件夹，重新安装，覆盖rime, 闪退
卸载同文，删除rime文件夹，重新安装，覆盖除build外的文件，点方案，出现提示无方案提示
选择下方恢复默认设置，恢复default.yaml，点方案，出现所有方案，勾选四叶草拼音和四叶草九宫，拼音可以正常输入，九宫仍不行

![Screenshot_20201218-134020](https://user-images.githubusercontent.com/27935867/102579069-b5426980-4136-11eb-88c5-769906b4bcf1.jpg)
![Screenshot_20201218-134038](https://user-images.githubusercontent.com/27935867/102579077-b70c2d00-4136-11eb-81ad-8f6262d8891c.jpg)
![image](https://user-images.githubusercontent.com/27935867/102579113-ce4b1a80-4136-11eb-99cc-941ed4fb5f6f.png)
![image](https://user-images.githubusercontent.com/27935867/102579130-d3a86500-4136-11eb-84d9-d0752ab55c75.png)
![image](https://user-images.githubusercontent.com/27935867/102579144-dc993680-4136-11eb-9a6d-4c7dc3b54965.png)

**Comment by SivanLaai** [comment]
你主题选用同文风就可以了，原本的主题是没有适配九宫的

**Comment by lgl017** [comment]
噢，可以了，感谢

**Comment by lgl017** [comment]
不过不知道是不是我的问题，在用release覆盖的过程中，build会导致闪退，default.yaml会读不到方案
另外还请在安装说明中加入主题要求，谢谢
