### ISSUE TITLE
如何在 最上面的 候選框添加一個粘貼選項？

### ISSUE THREAD

**Issue by ciskonc** [SivanLaai/rime_pure#9]
請問應該修改哪個文件來實現這個功能？

**Comment by SivanLaai** [comment]
这个已经实现了的，你长按字母G会进入编辑界面，有复制，粘贴和剪切等功能。不知道这个是不是你想要的，不是的话你就要修改主题文件了，对应后辍为.trime.yaml的文件。

**Comment by ciskonc** [comment]
好的，我的意思是打開輸入法後在候選框裏面直接多一個粘貼選項，按起來非常快。不需要進二級目錄點粘貼。我自己改改試試看。
